# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20160223_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='content',
            field=models.CharField(max_length=249),
        ),
    ]
