# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 00:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160225_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 26, 0, 7, 2, 112376, tzinfo=utc)),
        ),
    ]
