# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 01:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160225_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 26, 1, 43, 30, 144508, tzinfo=utc)),
        ),
    ]
